##############################################################
################## MODEL BUILDING SETTINGS ###################
##############################################################

######################
# METRICS MONITORING #
######################

# Experiment number for MLflow / Note that it is not possible
# to have the same experiment name multiple times
current_experiment: &current_exp experiment_0

# For monitoring metrics
mlflow:
  experiment_name: *current_exp
  tracking_uri: mlflow.get_tracking_uri()

########################
# Audio files settings #
########################
LENGTH_SEGMENTS: 3 # in seconds
SAMPLE_RATE: 44100

#################
# PATH SETTINGS #
#################

# Connection string if connecting to a remote server
# String in the form "ssh://user:password@host", can also be set to False
# if data is stored locally
CONNECTION_STRING: "ssh://user:password@host" # or set to False

# Path to the audio dataset used for training and validation
PATH_TRAIN_VAL_DATASET:  /data/tiny_training #"/cluster/projects/nn8055k/Model_training_data" 

# Path for storing Pytorch lightning logs
PATH_LIGHTNING_METRICS: "/app/"

# Path to the audio component of the test dataset 
TEST_PATH: '/data/test_dataset/audio'

# Path to the labels of the test dataset
TEST_DF_PATH: '/data/test_dataset/labels'

###########################
# Adding background noise #
###########################

# True or False
# True if you want to add other soundscape data to the audio file
IS_BG_NOISE: False

# True or False
# True if you want to add short noises to the audio file
IS_SHORT_NOISES: False

# If IS_BG_NOISE is True add the path to the folder containing
# the background noises
# !! PyfileSystem does not apply here so bg noise should be stored where the model is trained !!
PATH_BG_NOISE: "/data/Noise_background/soundscape"

# If IS_BG_NOISE is True add the path to the folder containing
# the background noises
# !! PyfileSystem does not apply here so bg noise should be stored where the model is trained !!
PATH_SHORT_NOISES: "/data/Noise_background/short_noises"

#####################
# TRAINING SETTINGS #
#####################

# fraction of the data to use for validation
PROP_TRAINING: 0.8 

# batch size used // DECREASE IF SHARED MEMORY PROBLEM
BATCH_SIZE: 32

# number of epochs to run, due to stopping rule this number just needs to be big
N_EPOCHS: 500

# number of epochs since last improvement before stopping training
STOPPING_RULE_PATIENCE: 10

# number of workers to use for data generation, change to 1 for debugging 
NUM_WORKERS: 4

# On what hardware to train the model. Options include: cpu, gpu or tpu
ACCELERATOR: "gpu" 

# Pin memory for the dataloader
PIN_MEMORY: True

# Learning rate to use. NOTE that if using ray.tune you can change to tune.loguniform
LEARNING_RATE: "tune.loguniform(0.0001, 0.1)"

# Number of output neurons for the model
NUM_TARGET_CLASSES: 2

#####################
# RAY TUNE SETTINGS #
#####################

# Name of the ray experiment
NAME_EXPERIMENT: "ray_experiment_0"

# Number of CPU available for each trial
N_CPU_PER_TRIAL: 4

# Number of GPU for each trial / NOTE THAT IN ITS CURRENT SETTINGS
# RAY TUNE USES ONE GPU FOR THE HEAD NODE, HAVE A LEAST 2 GPUS!!!
N_GPU_PER_TRIAL: 1

# Number of trials to do
N_SAMPLING: 20

# Ray tune saves some temp files in some folders that require root access
# It is possible to change the directory to avoid permission problems:
# For storing the ray tune results
LOCAL_DIR: "/app/" 

#######################
# TRANSFORMS SETTINGS #
#######################

# Regarding the choice of the augmentation see the post on StackExchange:
# https://bioacoustics.stackexchange.com/questions/98/data-augmentation-strategies-for-bioacoustics-machine-learning

# Parameters for the addition of Gaussian noise
GAUSSIAN_MIN_AMPLITUDE: 0.001
GAUSSIAN_MAX_AMPLITUDE: 0.015
GAUSSIAN_P: 0.5

# Parameters for SevenBandParametricEQ: 
# modifications to the frequency equalisation (this is similar to slightly 
# changing the response characteristics of your mic)
P_SEVENBANDPARAMETRICEQ: 0.5

# Time shifting
P_SHIFT: 0.5

# Parameters for AirAbsorption:
# emulating the effects of distance by adding a bit of low-pass filtering, 
# and/or some echo/reverb using an impulse response.
P_AIR_ABSORPTION: 0.5

# Time masking and frequency masking -- these don't have a very obvious interpretation but 
# are a kind of "dropout" of frequencies or time regions, and seem to help.
P_TIME_MASK: 0.5
P_FREQ_MASK: 0.5
