#############
# Data path #
#############

# Connection string if connecting to a remote server
# String in the form "ssh://user:password@host", can also be set to False
# if data is stored locally
CONNECTION_STRING: "ssh://user:password@host" # or set to False

# Folder containing the files that need predictions
INPUT_PATH: `/data/TO_PREDICT`

# Folder that will contain the output of the predictions
OUTPUT_PATH: '/data/PREDICTIONS/PREDS'

# Folder that will contain the extracted segments
OUT_PATH_SEGMENTS: '/data/PREDICTIONS/SEGMENTS'


##########################
# Model paths and config #
##########################

# Path to the saved model weights
MODEL: "./assets/anode.pth"

# Device where the model is to be run on, choose "cuda" or "cpu"
DEVICE: "cuda"

######################
# Inference settings #
######################

# Number of segments to extract
NUM_SEGMENTS: 30

