# training_parameters:
current_experiment: &current_exp experiment_4
train_val_dataset_path: "/Data/audioCLIP/tiny_training/**" # "/data/Prosjekter3/16784000_sats_22_51_rosten/Model_training_data/**"
path_lightning_metrics: "/app/"
proportion_training: 0.8 # fraction of the data to use for validation
batch_size: 16 #tune.choice([32, 64, 128]) # batch size used // INCREASE IF SHARED MEMORY PROBLEM
n_epoch: 10 # number of epochs to run, due to stopping rule this number just needs to be big
stopping_rule_patience: 5 # number of epochs since last improvement before stopping training
num_workers: 1 # number of workers to use for data generation, change to 1 for debugging // MODIFY IF SHARED MEMORY PROBLEM
accelerator: "cpu" # cpu, gpu or tpu
pin_memory: False
learning_rate: 0.01 #"tune.uniform(0.0001, 0.1)"

# Ray tune parameters
name_experiment: "ray_experiment_0"
n_cpu_per_trials: 2
n_gpu_per_trials: 0
n_sampling: 5

# transforms parameters:
length_segments: 3
max_scale: 1.25
p_random_flip: 0.2
crop: 132300
padding: 132300
sample_rate: 44100 # Value for resampling the audiofile

# For monitoring metrics
mlflow:
  experiment_name: *current_exp
  tracking_uri: mlflow.get_tracking_uri()

# Model parameters
num_target_classes: 2

# Parameters for the performance run
num_samples: 1

# Test parameters
cut_file_time: 1800
test_in_path: "/app/tiny_preds/YELLBTBC/Audio/*"
ckpts_path: "/app/assets/ckpt-exp0-lr0.001-val_loss=0.06.ckpt"
test_out_path: "/app/tiny_preds/v_small/"
label_correspondance: "/assets/label_correspondance.json"
pred_num_workers: 4
pred_batch_size: 8


