#################
# Misc settings #
#################

# Random seed for gaussian noise
RANDOM_SEED: 42

##########################
# Model paths and config #
##########################

# Path to the saved model weights
MODEL: "/app/assets/anode.pth"

# Device where the model is to be run on, choose "cuda" or "cpu"
DEVICE: "cpu"

##################
# Audio settings #
##################

# We use a sample rate of 48kHz, so the model input size is 
# (batch size, 48000 kHz * 3 seconds) = (1, 144000)
# Recordings will be resampled automatically.
SAMPLE_RATE: 44100

# We're using 3-second chunks
SIG_LENGTH: 3.0 

# Define overlap between consecutive chunks <3.0; 0 = no overlap
SIG_OVERLAP: 0 

# Define minimum length of audio chunk for prediction, 
# chunks shorter than 3 seconds will be padded with noise
SIG_MINLEN: 3.0 

######################
# Inference settings #
######################

# Sliding window overlap
OVERLAP: 0

# File containing the correspondance of the labels
LABELS_FILE: "/app/assets/label_correspondance.json"

# Folder containing the files that need predictions
INPUT_PATH: '/Data/audioCLIP/tiny_preds'

# Folder that will contain the output of the predictions
OUTPUT_PATH: '/Data/audioCLIP/results'

# Folder that will contain the extracted segments
OUT_PATH_SEGMENTS: '/Data/audioCLIP/segments'

# Number of segments to extract
NUM_SEGMENTS: 30

# Threshold to be used (note that it can be computed using bias_trade_of.py)
THRESHOLD: 0.97

# Number of threads to use for inference.
# Can be as high as number of CPUs in your system
NUM_WORKERS: 4

# Number of samples to process at the same time. Higher values can increase
# processing speed, but will also increase memory usage.
# Might only be useful for GPU inference.
BATCH_SIZE: 1

# Specifies the output format. 'table' denotes a Raven selection table,
# 'audacity' denotes a TXT file with the same format as Audacity timeline labels
# 'csv' denotes a CSV file with start, end, species and confidence.
RESULT_TYPE: 'table'